version: "3.5"
services:
  postgres:
    image: postgres:10.5-alpine
    volumes:
      - ./var/pg_data:/var/lib/postgresql/data
    env_file:
      - ./docker.env
  web:
    build: .
    # Production usage:
    command: /bin/sh -c "sleep 4 && gunicorn abudget.wsgi:application --workers=2 -b 0.0.0.0:5600"
    # Local development:
    # command: /bin/sh -c "sleep 4 && /src/manage.py runserver 0.0.0.0:5600"
    # useful for debug
    volumes:
      - ./src:/src
    ports:
      - "127.0.0.1:5600:5600"
    depends_on:
      - postgres
    env_file:
      - ./docker.env
